version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./db.sqlite:/usr/src/app/db.sqlite
    environment:
      - NODE_ENV=production
      - JWT_SECRET="your_secret_key"
      - PORT = 3000
